const jwt = require("jsonwebtoken");
const HttpError = require('../util/http-error-message');

module.exports = (req,res,next) => {

    // If there is an OPTIONS request generated by the browser then we have to permit it 
    if(req.method === "OPTIONS"){
        return next();
    }
    
    try{
        const token = req.headers.authorization.split(' ')[1];
        
        if(!token){
            throw new Error('Authentication Failed!');
        }

        const decoded = jwt.verify(token,'InnoventxRocks');
        req.userData = { userId: decoded.userId };
        next();
        
    }catch(err){
        console.log(err);
        return next(new HttpError('Authentication Failed!',500));
    }
}